version: '3.7'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - php
      - mysql
    command: ["dockerize", "-wait", "tcp://php:9000", "-timeout", "20s", "nginx", "-g", "daemon off;"]
    networks:
      - mynet
    restart: always

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: php
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      DB_HOST: 'mysql'
      DB_PORT: '3306'
      DB_DATABASE: 'ip4y'
      DB_USERNAME: 'root'
      DB_PASSWORD: ''
    networks:
      - mynet
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'ip4y'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynet
    restart: always

  migrate:
    image: ip4y_php
    container_name: migrate
    depends_on:
      - php
    volumes:
      - .:/var/www/html
    entrypoint: ["sh", "-c", "php artisan migrate"]
    networks:
      - mynet

networks:
  mynet:
    driver: bridge

volumes:
  mysql_data:
